name: CI
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.4.1
      with:
        clang-format-version: '13'
        check-path: 'nn-hal'
  build:
    needs: clang-format
    runs-on: self-hosted
    environment: development
    env:
      ROOT_DIR: /opt/chromeos/workspace
      REPO_NAME: intel-nnhal-dev
    steps:
    - name: Build and deploy nn-hal.
      run: |
        echo ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
        cd ${ROOT_DIR}/src/third_party/
        rm -rf ${REPO_NAME}
        git clone ${{ github.server_url }}/${{ github.repository }} ${REPO_NAME}
        cd ${REPO_NAME}
        git checkout ${{ github.sha }}
        cp ci/* ${ROOT_DIR}/src/
        cd ${ROOT_DIR}/src/
        sh build-test.sh "build"
  test-functional:
    needs: build
    runs-on: self-hosted
    env:
      ROOT_DIR: /opt/chromeos/workspace
    steps:
    - name: Run functional tests for nn-hal.
      run: |
        cd ${ROOT_DIR}/src/
        sh build-test.sh "functional"
