name: CI
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.4.1
      with:
        clang-format-version: '13'
        check-path: 'nn-hal'
